language: python
python:
    - "2.7"
install: 
    - "python setup.py install"
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coveralls --use-mirrors"
script: "coverage run --source=hn setup.py test"
script:
    - nosetests --with-coverage --cover-package=flask_slither
after_success: "coveralls"
notifications:
  email: false